version: '3.9'
services:
  metabase:
# Uncomment line "build" for build metabase, but, comment line "image: bobblybook/metabase:v0.48.4"
#    build: ./build
    image: bobblybook/metabase:v0.48.4
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    - ./data:/app
    ports:
      - 3010:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: metabase_postgres 
    restart: always
    networks:
      - metabase
    secrets:
      - db_password
      - db_user
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  metabase_postgres:
    image: postgres:latest
    container_name: matabase_postgres
    hostname: metabase_postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql/data/
    networks:
      - metabase
    secrets:
      - db_password
      - db_user
networks:
  metabase:
    driver: bridge
secrets:
   db_password:
     file: db_password.txt
   db_user:
     file: db_user.txt
